#!/bin/bash

# Script para verificar recursos disponibles en el cluster
# y determinar qué nodo es más apropiado para Llama2-7B cuantizado

echo "=============================================================================="
echo "  VERIFICACIÓN DE RECURSOS DEL CLUSTER"
echo "=============================================================================="
echo ""

# Información sobre nodos disponibles
echo "📊 INFORMACIÓN DE NODOS DISPONIBLES"
echo "=============================================================================="
echo ""

# Cola student.q
echo "🔵 COLA: student.q"
echo "  - pcgtx1080:  GTX 1080 (8GB VRAM)"
echo "  - pcgtx1070:  GTX 1070 (8GB VRAM)"
echo "  - pcgtx970:   GTX 970  (4GB VRAM)"
echo ""

# Cola tfm.q
echo "🔵 COLA: tfm.q"
echo "  - deimos:     ??? (desconocido, necesita verificación)"
echo "  - phobos:     ??? (desconocido, necesita verificación)"
echo ""

echo "=============================================================================="
echo "  REQUISITOS DEL TRABAJO"
echo "=============================================================================="
echo ""
echo "Modelo: Llama2-7B-hf (7 billones de parámetros)"
echo "Cuantización: 4-bit (bitsandbytes)"
echo ""
echo "Memoria VRAM requerida:"
echo "  - Tokenizer cargado:           ~500 MB"
echo "  - Modelo 7B en 4-bit:          ~4.5-5.0 GB"
echo "  - Buffer para inference:       ~2.0 GB"
echo "  - TOTAL RECOMENDADO:           ~7.0-8.0 GB"
echo ""
echo "Requisitos adicionales:"
echo "  - PyTorch 2.4.1+cu118 (requiere CUDA 11.8+)"
echo "  - bitsandbytes (requiere NVIDIA GPU con compute capability 7.0+)"
echo "  - Conexión de red a HuggingFace Hub (descarga de modelos)"
echo ""

echo "=============================================================================="
echo "  ANÁLISIS DE COMPATIBILIDAD"
echo "=============================================================================="
echo ""

echo "📌 GTX 1080 (student.q@pcgtx1080)"
echo "  VRAM:                8GB"
echo "  Compute Capability:  6.1"
echo "  Soporte bitsandbytes: ⚠️  PARCIAL (bitsandbytes requiere CC 7.0+)"
echo "  Compatibilidad:      ⚠️  MARGINAL - Puede funcionar con optimizaciones"
echo ""

echo "📌 GTX 1070 (student.q@pcgtx1070)"
echo "  VRAM:                8GB"
echo "  Compute Capability:  6.1"
echo "  Soporte bitsandbytes: ⚠️  PARCIAL (bitsandbytes requiere CC 7.0+)"
echo "  Compatibilidad:      ⚠️  MARGINAL - Puede funcionar con optimizaciones"
echo ""

echo "📌 GTX 970 (student.q@pcgtx970)"
echo "  VRAM:                4GB"
echo "  Compute Capability:  5.2"
echo "  Soporte bitsandbytes: ❌ NO (insuficiente VRAM + CC antigua)"
echo "  Compatibilidad:      ❌ INCOMPATIBLE - No recomendado"
echo ""

echo "📌 Deimos (tfm.q@deimos)"
echo "  VRAM:                DESCONOCIDO"
echo "  Compute Capability:  DESCONOCIDO"
echo "  Soporte bitsandbytes: ❓ NECESITA VERIFICACIÓN"
echo "  Compatibilidad:      ❓ POTENCIALMENTE ÓPTIMA (si tiene GPU moderna)"
echo ""

echo "📌 Phobos (tfm.q@phobos)"
echo "  VRAM:                DESCONOCIDO"
echo "  Compute Capability:  DESCONOCIDO"
echo "  Soporte bitsandbytes: ❓ NECESITA VERIFICACIÓN"
echo "  Compatibilidad:      ❓ POTENCIALMENTE ÓPTIMA (si tiene GPU moderna)"
echo ""

echo "=============================================================================="
echo "  RECOMENDACIONES"
echo "=============================================================================="
echo ""
echo "1️⃣  PRIMERA OPCIÓN: Nodos deimos o phobos (tfm.q)"
echo "   - Probablemente con GPUs más modernas (RTX, V100, A100, etc.)"
echo "   - Si tienen A100 o V100: ✅ ÓPTIMO"
echo "   - Si tienen RTX series (RTX2080Ti, RTX3090, etc.): ✅ EXCELENTE"
echo ""
echo "2️⃣  SEGUNDA OPCIÓN: GTX 1080 o GTX 1070 (student.q)"
echo "   - Sufficient VRAM (8GB)"
echo "   - ⚠️  Soporte bitsandbytes limitado por Compute Capability"
echo "   - Requiere compilación local o versión CPU-compatible"
echo ""
echo "3️⃣  EVITAR: GTX 970 (student.q)"
echo "   - Insuficiente VRAM (4GB)"
echo "   - Compute Capability demasiado antigua (5.2)"
echo ""

echo "=============================================================================="
echo "  PRÓXIMOS PASOS"
echo "=============================================================================="
echo ""
echo "Para verificar exactamente qué GPUs hay en deimos y phobos, ejecuta:"
echo ""
echo "  qstat -f -h deimos"
echo "  qstat -f -h phobos"
echo ""
echo "O intenta con SSH:"
echo ""
echo "  ssh deimos 'nvidia-smi'"
echo "  ssh phobos 'nvidia-smi'"
echo ""
echo "Para verificar Compute Capability:"
echo ""
echo "  ssh deimos 'nvidia-smi -q | grep Compute'"
echo "  ssh phobos 'nvidia-smi -q | grep Compute'"
echo ""

echo "=============================================================================="
echo "  SCRIPTS DE PRUEBA"
echo "=============================================================================="
echo ""
echo "Se han creado scripts para testing en cluster:"
echo ""
echo "  submit_test_cluster.sh     - Script para enviar test rápido al cluster"
echo "  submit_tokenizer_cluster.sh - Script para tokenizer (ligero)"
echo "  submit_model_cluster.sh     - Script para cargar modelo completo"
echo ""
echo "Uso:"
echo "  qsub -q student.q@pcgtx1080 submit_test_cluster.sh"
echo "  qsub -q tfm.q@deimos submit_model_cluster.sh"
echo "  qsub -q tfm.q@phobos submit_model_cluster.sh"
echo ""

echo "=============================================================================="
